# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.categories_controller:
        class: AppBundle\Controller\CategoriesController
    app.products_controller:
        class: AppBundle\Controller\ProductsController